name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      draft:
        description: 'Create as draft release'
        required: false
        type: boolean
        default: true

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete existing release if exists
        continue-on-error: true
        run: |
          gh release delete ${{ github.event.inputs.version }} --yes --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: false

  build-linux-x64:
    name: Build Linux x64
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libxxf86vm-dev

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Strip binary
        run: strip --strip-all build/FabricBinarySearch

      - name: Create archive
        run: |
          mkdir -p dist
          cp build/FabricBinarySearch dist/
          tar -czf FabricBinarySearch-linux-x64.tar.gz -C dist .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: FabricBinarySearch-linux-x64.tar.gz
          asset_name: FabricBinarySearch-linux-x64.tar.gz
          asset_content_type: application/gzip

  build-macos-x64:
    name: Build macOS x64
    needs: create-release
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install pkg-config cmake ninja

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=x86_64 -G Ninja

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Strip binary
        run: strip build/FabricBinarySearch

      - name: Create archive
        run: |
          mkdir -p dist
          cp build/FabricBinarySearch dist/
          tar -czf FabricBinarySearch-macos-x64.tar.gz -C dist .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: FabricBinarySearch-macos-x64.tar.gz
          asset_name: FabricBinarySearch-macos-x64.tar.gz
          asset_content_type: application/gzip

  build-macos-arm64:
    name: Build macOS ARM64
    needs: create-release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install pkg-config cmake ninja

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64 -G Ninja

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Strip binary
        run: strip build/FabricBinarySearch

      - name: Create archive
        run: |
          mkdir -p dist
          cp build/FabricBinarySearch dist/
          tar -czf FabricBinarySearch-macos-arm64.tar.gz -C dist .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: FabricBinarySearch-macos-arm64.tar.gz
          asset_name: FabricBinarySearch-macos-arm64.tar.gz
          asset_content_type: application/gzip

  build-windows-x64:
    name: Build Windows x64
    needs: create-release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -A x64

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Create archive
        run: |
          mkdir -p dist
          cp build/Release/FabricBinarySearch.exe dist/
          7z a FabricBinarySearch-windows-x64.zip .\dist\*

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: FabricBinarySearch-windows-x64.zip
          asset_name: FabricBinarySearch-windows-x64.zip
          asset_content_type: application/zip

  build-windows-arm64:
    name: Build Windows ARM64
    needs: create-release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -A ARM64

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Create archive
        run: |
          mkdir -p dist
          cp build/Release/FabricBinarySearch.exe dist/
          7z a FabricBinarySearch-windows-arm64.zip .\dist\*

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: FabricBinarySearch-windows-arm64.zip
          asset_name: FabricBinarySearch-windows-arm64.zip
          asset_content_type: application/zip

  finalize-release:
    name: Finalize Release
    needs: 
      - create-release
      - build-linux-x64
      - build-macos-x64
      - build-macos-arm64
      - build-windows-x64
      - build-windows-arm64
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: always()
    steps:
      - name: Update release status
        run: |
          if ${{ needs.build-linux-x64.result == 'success' && needs.build-macos-x64.result == 'success' && needs.build-macos-arm64.result == 'success' && needs.build-windows-x64.result == 'success' && needs.build-windows-arm64.result == 'success' }}; then
            echo "All builds completed successfully!"
          else
            echo "Some builds failed. Check the logs."
          fi
